# Generated by Django 6.1.1 on 2026-09-19 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('sample', 'Test sample'), ('csv', 'CSV upload'), ('pasted', 'Pasted values')], max_length=10)),
                ('source_name', models.CharField(blank=True, help_text='File name, or a description of where the values came from.', max_length=255)),
                ('features', models.JSONField(help_text='The 60 sonar readings that were classified.')),
                ('predicted_label', models.CharField(choices=[('M', 'Mine'), ('R', 'Rock')], max_length=1)),
                ('confidence', models.FloatField(help_text='Probability of the predicted class (0-1).')),
                ('probability_mine', models.FloatField(help_text='Probability the target is a mine (0-1).')),
                ('true_label', models.CharField(blank=True, choices=[('M', 'Mine'), ('R', 'Rock')], help_text='Only known for test samples.', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='predictor_p_user_id_ec23bd_idx')],
            },
        ),
    ]
